settings:
  legacy:
    force: false
    interval: 0s
schema:
- name: realize-sample
  path: .
  commands: 
    run:
      status: true
  watcher:
    paths:
    - /
    extensions:
    - go
    ignored_paths:
    - .git
    - .realize
    - vendor
